# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Assignment5-NailStocks' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Assignment5-NailStocks
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 5.5'
  pod "SwiftSpinner"

end
